/**
 * Type definitions for Cajurona database
 * These would normally be auto-generated by Supabase CLI
 */

/**
 * @typedef {'ida' | 'volta'} TipoViagem
 * @typedef {'agendada' | 'em_andamento' | 'concluida' | 'cancelada'} StatusViagem
 * @typedef {'confirmado' | 'cancelado' | 'pendente' | 'atrasado'} StatusPresenca
 */

/**
 * @typedef {Object} Grupo
 * @property {string} id
 * @property {string} nome
 * @property {string|null} whatsapp_group_id
 * @property {string|null} motorista_id
 * @property {number} valor_semanal
 * @property {string} horario_ida
 * @property {string} horario_volta
 * @property {string} created_at
 * @property {string} updated_at
 */

/**
 * @typedef {Object} Membro
 * @property {string} id
 * @property {string} grupo_id
 * @property {string} nome
 * @property {string} telefone
 * @property {string|null} whatsapp_id
 * @property {string[]} dias_padrao
 * @property {boolean} is_motorista
 * @property {boolean} ativo
 * @property {string} created_at
 * @property {string} updated_at
 */

/**
 * @typedef {Object} Viagem
 * @property {string} id
 * @property {string} grupo_id
 * @property {string} data
 * @property {TipoViagem} tipo
 * @property {string} horario_partida
 * @property {StatusViagem} status
 * @property {string} created_at
 */

/**
 * @typedef {Object} Presenca
 * @property {string} id
 * @property {string} viagem_id
 * @property {string} membro_id
 * @property {StatusPresenca} status
 * @property {string|null} horario_atraso
 * @property {string|null} observacao
 * @property {string|null} confirmado_em
 * @property {string} created_at
 */

export const DIAS_SEMANA = ['seg', 'ter', 'qua', 'qui', 'sex'];
export const DIAS_SEMANA_FULL = {
    'seg': 'Segunda',
    'ter': 'Terça',
    'qua': 'Quarta',
    'qui': 'Quinta',
    'sex': 'Sexta'
};
